- name: remove shadowproxy
  docker_container:
    name: "{{shadowproxy_container_name}}"
    state: absent
  when: state == "absent"

- name: start shadowproxy container
  docker_container:
     ports:
         - "443:443"
     name: "{{ shadowproxy_container_name }}"
     image: guchman/docker-shadowsocks-go2:alpine
     state: started
     restart: yes
     restart_policy: unless-stopped
     command: ["-s", "ss://{{ crypto_method }}:{{ proxy_pass }}@:443", "-verbose", "-u"]
  when: state == "started"