- name: Ensure that Python3 packages are installed
  package:
    name: "{{item}}"
    state: present
  with_items: "{{ python_apt_packages_3 }}"
  when: python_install_3

- name: Update pip
  package:
    name: "pip{% if python_pip_version is defined %}=={{ python_pip_version }}{% endif %}"
    state: present
  when: python_update_pip

- name: Update setuptools
  package:
    name: "setuptools{% if python_setuptools_version is defined %}=={{ python_setuptools_version }}{% endif %}"
    state: present
  when: python_update_setuptools

- name: Install custom python requirements
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_pip_packages }}"

- name: Install virtualenv
  pip:
    package: "virtualenv{% if python_virtualenv_version is defined %}=={{ python_virtualenv_version }}{% endif %}"
    state: present
  when: python_install_virtualenv

- name: Install virtualenv
  pip:
    name: "docker-py"
    state: present